# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: mariadb:11.1
    restart: always
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 9081:80
      - 9025:25


#  microcontenu:
#    container_name: blogging
#    image: microcontenu:0.0.1-SNAPSHOT
#    depends_on:
#      - database
#    ports:
#      - 8090:8080
#    links:
#      - database
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/blogcontenue
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
